In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('ONINE_FOOD_DELIVERY_ANALYSIS.csv')
data.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,08-12-2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12-08-2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10-08-2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,02-04-2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [3]:
data.shape

(100000, 25)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [5]:
data.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [6]:
missing_count = data.isnull().sum()
print(missing_count)

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [7]:
missing_pct = (data.isnull().sum()/len(data))*100
print(missing_pct)

Order_ID                0.000
Customer_ID             0.000
Customer_Age           50.093
Customer_Gender        24.856
City                   16.726
Area                   16.685
Restaurant_ID           0.000
Restaurant_Name         0.000
Cuisine_Type           16.885
Order_Date              1.014
Order_Time              1.998
Delivery_Time_Min      33.359
Distance_km            33.470
Order_Value            33.327
Discount_Applied       16.715
Final_Amount           55.697
Payment_Mode           19.911
Order_Status            0.000
Cancellation_Reason    90.969
Delivery_Partner_ID     0.000
Delivery_Rating        16.523
Restaurant_Rating       0.000
Order_Day               0.000
Peak_Hour              32.962
Profit_Margin           0.000
dtype: float64



*   cancellation_reason     - 90
*   customer_age       -50


*   final amount        55
*   Delivery_Time_Min, Distance_km, Order_Value      	33

*   peak hour        32

*  customer gender    24

*   payment mode     -19
*   city, area,cuisine type ,discount applied, delivery rating-    16

In [8]:
#Handle missing value
numeric = data.select_dtypes(include = ['int64','float64']).columns
numeric

Index(['Customer_Age', 'Delivery_Time_Min', 'Distance_km', 'Order_Value',
       'Discount_Applied', 'Final_Amount', 'Delivery_Rating',
       'Restaurant_Rating', 'Profit_Margin'],
      dtype='object')

In [9]:
data.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [10]:
numeric = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Percentage': missing_pct,
    'Data type': data.dtypes
})

print(numeric[numeric['Missing Count'] > 0].sort_values('Missing Percentage', ascending=False))

                     Missing Count  Missing Percentage Data type
Cancellation_Reason          90969              90.969    object
Final_Amount                 55697              55.697   float64
Customer_Age                 50093              50.093   float64
Distance_km                  33470              33.470   float64
Delivery_Time_Min            33359              33.359   float64
Order_Value                  33327              33.327   float64
Peak_Hour                    32962              32.962    object
Customer_Gender              24856              24.856    object
Payment_Mode                 19911              19.911    object
Cuisine_Type                 16885              16.885    object
City                         16726              16.726    object
Discount_Applied             16715              16.715   float64
Area                         16685              16.685    object
Delivery_Rating              16523              16.523   float64
Order_Time                    1998               1.998    object
Order_Date                    1014               1.014    object

In [11]:
numeric

                     Missing Count  Missing Percentage Data type
Order_ID                         0               0.000    object
Customer_ID                      0               0.000    object
Customer_Age                 50093              50.093   float64
Customer_Gender              24856              24.856    object
City                         16726              16.726    object
Area                         16685              16.685    object
Restaurant_ID                    0               0.000    object
Restaurant_Name                  0               0.000    object
Cuisine_Type                 16885              16.885    object
Order_Date                    1014               1.014    object
Order_Time                    1998               1.998    object
Delivery_Time_Min            33359              33.359   float64
Distance_km                  33470              33.470   float64
Order_Value                  33327              33.327   float64
Discount_Applied             16715              16.715   float64
Final_Amount                 55697              55.697   float64
Payment_Mode                 19911              19.911    object
Order_Status                     0               0.000    object
Cancellation_Reason          90969              90.969    object
Delivery_Partner_ID              0               0.000    object
Delivery_Rating              16523              16.523   float64
Restaurant_Rating                0               0.000   float64
Order_Day                        0               0.000    object
Peak_Hour                    32962              32.962    object
Profit_Margin                    0               0.000   float64

In [12]:
skew_values = data[['Customer_Age',
 'Delivery_Time_Min',
 'Distance_km',
 'Order_Value',
 'Discount_Applied',
 'Final_Amount',
 'Delivery_Rating',
 'Restaurant_Rating',
 'Profit_Margin']].skew()
print(skew_values)

Customer_Age        -0.002988
Delivery_Time_Min    0.409811
Distance_km          0.411771
Order_Value          0.376555
Discount_Applied     1.168823
Final_Amount         0.380548
Delivery_Rating      0.006127
Restaurant_Rating    0.000743
Profit_Margin       -0.006315
dtype: float64

In [13]:
data.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [14]:
numeric = ['Customer_Age', 'Delivery_Time_Min', 'Distance_km', 'Order_Value',
       'Discount_Applied', 'Final_Amount', 'Delivery_Rating',
       'Restaurant_Rating', 'Profit_Margin']
#handling mean
mean = mean_cols = ['Customer_Age','Order_Value','Delivery_Rating',
                    'Restaurant_Rating','Profit_Margin']

median = ['Delivery_Time_Min','Distance_km','Discount_Applied',
          'Final_Amount']
#fill with mean
for cols in mean:
  data[cols].fillna(data[cols].mean(),inplace= True)

#fill with median
for cols in median:
  data[cols].fillna(data[cols].median(),inplace = True)

In [15]:
categorical = data.select_dtypes(include=['object','category']).columns
categorical

Index(['Order_ID', 'Customer_ID', 'Customer_Gender', 'City', 'Area',
       'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type', 'Order_Date',
       'Order_Time', 'Payment_Mode', 'Order_Status', 'Cancellation_Reason',
       'Delivery_Partner_ID', 'Order_Day', 'Peak_Hour'],
      dtype='object')

In [16]:
#fill with mode
for cols in categorical:
  data[cols].fillna(data[cols].mode()[0],inplace=True)

In [17]:
#duplicate
data.duplicated().sum()

np.int64(0)

In [18]:
#convert data types
from datetime import date
# ID columns
id_cols = ['Order_ID','Customer_ID','Restaurant_ID','Delivery_Partner_ID']
for col in id_cols:
    data[col] = data[col].astype(str)

# categorical columns
cat_cols = ['Customer_Gender','City','Area','Cuisine_Type',
            'Payment_Mode','Order_Status','Cancellation_Reason']
for col in cat_cols:
    data[col] = data[col].astype('category')

# date columns
data['Order_Date'] = pd.to_datetime(data['Order_Date'], errors='coerce')
data['Order_Time'] = pd.to_datetime(data['Order_Time'], errors='coerce')

# numeric columns
num_cols = ['Customer_Age','Distance_km','Order_Value',
            'Discount_Applied','Final_Amount','Delivery_Rating',
            'Restaurant_Rating','Profit_Margin']

In [19]:
for col in num_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# special case (int)
data['Delivery_Time_Min'] = data['Delivery_Time_Min'].fillna(0).astype(int)

In [20]:
#check invalid numeric values
['Customer_Age','Delivery_Time_Min','Distance_km',
'Order_Value','Final_Amount','Profit_Margin','Delivery_Rating',
'Restaurant_Rating']
data[data['Customer_Age']<0]
data[(data['Delivery_Time_Min']<30)|(data['Delivery_Time_Min']>90)]
data[data['Delivery_Rating']<1|(data['Delivery_Rating']>5)]
data[data['Restaurant_Rating']<1|(data['Restaurant_Rating']>5)]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Age, Customer_Gender, City, Area, Restaurant_ID, Restaurant_Name, Cuisine_Type, Order_Date, Order_Time, Delivery_Time_Min, Distance_km, Order_Value, Discount_Applied, Final_Amount, Payment_Mode, Order_Status, Cancellation_Reason, Delivery_Partner_ID, Delivery_Rating, Restaurant_Rating, Order_Day, Peak_Hour, Profit_Margin]
Index: []

[0 rows x 25 columns]

In [21]:
#check date & time format
data['Order_Date'] = pd.to_datetime(data['Order_Date'], errors='coerce')
data['Order_Date'].fillna(data['Order_Date'].mode()[0],inplace = True)
data['Order_Time'] = pd.to_datetime(data['Order_Time'], errors='coerce').dt.time

In [22]:
data[['Order_Date','Order_Time']]

      Order_Date Order_Time
0     2024-10-20   00:00:00
1     2024-07-15   00:00:00
2     2024-07-15   00:00:00
3     2024-07-15   00:00:00
4     2024-07-15   00:00:00
...          ...        ...
99995 2024-07-15   00:00:00
99996 2024-04-22   00:00:00
99997 2024-02-23   00:00:00
99998 2024-07-15   00:00:00
99999 2024-07-15   00:00:00

[100000 rows x 2 columns]

In [23]:
#handling string operation

#remove special charcters
data['Cuisine_Type'] = data['Cuisine_Type'].str.replace(r'[^a-zA-Z\s]', '', regex=True)
#standaredize gender value
data['Customer_Gender'] = data['Customer_Gender'].str.replace(r'(?i)^m.*', 'Male', regex=True)
data['Customer_Gender'] = data['Customer_Gender'].str.replace(r'(?i)^f.*', 'Female', regex=True)
#standardize payment mode
data['Payment_Mode'] = data['Payment_Mode'].str.title()
#remove multiple space
data['Area'] = data['Area'].str.replace(r'\s+', ' ', regex=True)
#detcet invalid charcters
data[data['City'].str.contains(r'[^a-zA-Z\s]', na=False)]
#check unique values
data['Peak_Hour'].unique()

array([ True, False])

In [24]:
#check string inconsistent data
data_inconsistent = {
    'Customer_Gender':['Female', 'Male', 'Other'],
    'City': ['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai'],
    'Area': ['Central', 'East', 'North', 'South', 'West'],
    'Cuisine_Type':['Arabian', 'Chinese', 'Indian', 'Italian', 'Mexican'],
    'Payment_Mode':['COD', 'Card', 'UPI', 'Wallet'],
    'Order_Status':['Cancelled', 'Delivered'],
    'Cancellation_Reason': ['Customer Cancelled', 'Late Delivery', 'Restaurant Issue']

}

In [25]:
#standardize
data['Customer_Gender'] = data['Customer_Gender'].str.lower().replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    'others': 'Other',
    'other': 'Other'
})

data['City'] = data['City'].str.lower().replace({
    'che':'Chennai',
    'chennai':'Chennai',

    'delhi' :'Delhi',
    'mumbai':'Mumbai',
    'bangalore':'Bangalore',
    'hyderabad':'Hyderabad'
})

data['Area'] = data['Area'].str.lower().str.lower().replace({
    'central':'Central',
    'north':'North',
    'south':'South',
    'east':'East',
    'west':'West'
})

data["Cuisine_Type"] = data["Cuisine_Type"].str.lower().replace({
    "arabian": "Arabian",
    "indian": "South Indian",
    "chinese": "Chinese",
    "italian":"Italian",
    "mexican":"Mexican"
})

data['Payment_Mode'] = data['Payment_Mode'].str.lower().replace({
    "upi payment" :"UPI",
    "upi_payement": "UPI",
    "Cash On Delivery":"COD",
    'cod':'COD',
    'card':'Card',
    "Card":"Card",
    "Wallet":"Wallet"
})

data['Cancellation_Reason'] = data['Cancellation_Reason'].str.lower().replace({
    'late delivery':'Late Delivery',
    'restaurant issue':'Restaurant Issue',
    'customer cancelled':'Customer Cancelled'
})

In [26]:
#check logical inconsistency
#delivered  should not have c.reason
data[(data['Order_Status']=='Delivered') & (data['Cancellation_Reason'].isna())]
#cancelled  - have reasons
data[(data['Order_Status'] == 'Cancelled') & (data['Cancellation_Reason'].isna())]
#final amount should not exceed order value
data[data['Final_Amount'] > data['Order_Value']]

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
24,ORD000025,CUST9940,45.000000,Other,Chennai,South,RES953,Restaurant_189,Italian,2024-07-15,...,1156.0,wallet,Delivered,Late Delivery,DP416,4.000000,5.1,Weekday,True,0.45
26,ORD000027,CUST5294,42.000000,Other,Chennai,South,RES247,Restaurant_47,South Indian,2024-10-30,...,1156.0,wallet,Delivered,Late Delivery,DP374,3.000000,4.3,Weekday,True,0.16
31,ORD000032,CUST5261,38.976516,Female,Delhi,Central,RES403,Restaurant_270,Italian,2024-07-15,...,1156.0,wallet,Cancelled,Late Delivery,DP441,2.991531,3.2,Weekday,False,0.12
52,ORD000053,CUST1336,38.976516,Male,Mumbai,Central,RES424,Restaurant_2,Mexican,2024-08-30,...,1156.0,COD,Delivered,Late Delivery,DP775,4.000000,3.9,Weekday,True,0.30
143,ORD000144,CUST4546,38.976516,Female,Hyderabad,West,RES637,Restaurant_397,Italian,2024-07-15,...,1156.0,Card,Delivered,Late Delivery,DP601,5.000000,3.3,Weekday,False,0.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99946,ORD099947,CUST7047,53.000000,Other,Bangalore,East,RES941,Restaurant_143,Mexican,2024-10-17,...,1156.0,upi,Cancelled,Restaurant Issue,DP792,4.000000,3.4,Weekday,True,0.27
99960,ORD099961,CUST5198,38.976516,Other,Delhi,South,RES732,Restaurant_94,South Indian,2024-07-15,...,1156.0,COD,Cancelled,Late Delivery,DP383,4.000000,3.6,Weekday,False,0.03
99972,ORD099973,CUST3551,41.000000,Other,Mumbai,Central,RES197,Restaurant_254,South Indian,2024-07-30,...,1156.0,Card,Delivered,Late Delivery,DP213,4.000000,5.1,Weekday,False,0.22
99974,ORD099975,CUST1412,38.976516,Other,Chennai,South,RES389,Restaurant_83,Arabian,2024-08-16,...,1156.0,Card,Delivered,Late Delivery,DP594,5.000000,3.6,Weekday,False,0.10
99982,ORD099983,CUST3056,44.000000,Male,Hyderabad,East,RES583,Restaurant_495,Chinese,2024-06-26,...,1156.0,COD,Delivered,Late Delivery,DP814,5.000000,5.1,Weekday,False,-0.10

In [27]:
#numeric range validation
# age should be positive
data = data[data['Customer_Age'] > 0]
# distance should not be negative
data = data[data['Distance_km'] >= 0]
# ratings must be between 1 and 5
data = data[(data['Delivery_Rating'] >= 1) & (data['Delivery_Rating'] <= 5)]

In [28]:
numeric

['Customer_Age',
 'Delivery_Time_Min',
 'Distance_km',
 'Order_Value',
 'Discount_Applied',
 'Final_Amount',
 'Delivery_Rating',
 'Restaurant_Rating',
 'Profit_Margin']

In [29]:
(data[['Customer_Age', 'Delivery_Time_Min', 'Distance_km', 'Order_Value',
       'Discount_Applied', 'Final_Amount', 'Delivery_Rating', 'Restaurant_Rating',
       'Profit_Margin']].skew())

Customer_Age        -0.004230
Delivery_Time_Min    0.600823
Distance_km          0.993028
Order_Value          0.461158
Discount_Applied     1.435932
Final_Amount         1.528915
Delivery_Rating      0.006706
Restaurant_Rating    0.000743
Profit_Margin       -0.006315
dtype: float64

In [30]:
(data['Customer_Age'].skew())*100

np.float64(-0.4230129357470064)

for customer age & restaturant rating no need to handel outliers because -0.42 & 0.07

In [31]:
#outlier
#n0rmal
outlier_cols = ['Delivery_Rating']
for col in outlier_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower) | (data[col] > upper)]

    print(f"{col} → {len(outliers)} outliers ({len(outliers)/len(data)*100:.2f}%)")

Delivery_Rating → 0 outliers (0.00%)

In [32]:
#removing outliers #high skewed
cols =['Delivery_Time_Min', 'Distance_km','Order_Value',
       'Discount_Applied','Final_Amount','Profit_Margin']

for col in cols:

        lower = data[col].quantile(0.01)
        upper = data[col].quantile(0.99)

        outliers = data[
            (data[col] < lower) |
            (data[col] > upper)
        ]

        print(f"{col} → {len(outliers)} outliers ({len(outliers)/len(data)*100:.2f}%)")

        # Now clip
        data[col] = data[col].clip(lower, upper)

Delivery_Time_Min → 1549 outliers (1.55%)
Distance_km → 1986 outliers (1.99%)
Order_Value → 1975 outliers (1.98%)
Discount_Applied → 0 outliers (0.00%)
Final_Amount → 1996 outliers (2.00%)
Profit_Margin → 1492 outliers (1.49%)

In [33]:
data.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Order_Time', 'Delivery_Time_Min', 'Distance_km',
       'Order_Value', 'Discount_Applied', 'Final_Amount', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Delivery_Partner_ID',
       'Delivery_Rating', 'Restaurant_Rating', 'Order_Day', 'Peak_Hour',
       'Profit_Margin'],
      dtype='object')

In [34]:
#Feature Engineering

data['Profit_Margin'] = data['Final_Amount'] - data['Order_Value']

# weekend indicator
data['Day_Type'] = data['Order_Day'].apply(
    lambda x: 'Weekend' if x in ['Saturday','Sunday'] else 'Weekday'
)

# extract hour from time
data['Order_Hour'] = data['Order_Time'].apply(lambda x: x.hour if pd.notnull(x) else None)

# peak hour indicator
data['Peak_Hour'] = data['Order_Hour'].apply(
    lambda x: 1 if x in range(18,23) else 0
)

# delivery performance
data['Delivery_Performance'] = data['Delivery_Time_Min'].apply(
    lambda x: 'Fast' if x < 30 else ('Average' if x <= 60 else 'Slow')
)

# age group
data['Age_Group'] = data['Customer_Age'].apply(
    lambda x: 'Young' if x < 25 else ('Adult' if x <= 40 else 'Senior')
)

In [35]:
data.isnull().sum()

Order_ID                0
Customer_ID             0
Customer_Age            0
Customer_Gender         0
City                    0
Area                    0
Restaurant_ID           0
Restaurant_Name         0
Cuisine_Type            0
Order_Date              0
Order_Time              0
Delivery_Time_Min       0
Distance_km             0
Order_Value             0
Discount_Applied        0
Final_Amount            0
Payment_Mode            0
Order_Status            0
Cancellation_Reason     0
Delivery_Partner_ID     0
Delivery_Rating         0
Restaurant_Rating       0
Order_Day               0
Peak_Hour               0
Profit_Margin           0
Day_Type                0
Order_Hour              0
Delivery_Performance    0
Age_Group               0
dtype: int64

In [36]:
print("\nFinal Missing Values:\n", data.isnull().sum())
print("\nFinal Shape:", data.shape)

Final Missing Values:
 Order_ID                0
Customer_ID             0
Customer_Age            0
Customer_Gender         0
City                    0
Area                    0
Restaurant_ID           0
Restaurant_Name         0
Cuisine_Type            0
Order_Date              0
Order_Time              0
Delivery_Time_Min       0
Distance_km             0
Order_Value             0
Discount_Applied        0
Final_Amount            0
Payment_Mode            0
Order_Status            0
Cancellation_Reason     0
Delivery_Partner_ID     0
Delivery_Rating         0
Restaurant_Rating       0
Order_Day               0
Peak_Hour               0
Profit_Margin           0
Day_Type                0
Order_Hour              0
Delivery_Performance    0
Age_Group               0
dtype: int64

Final Shape: (100000, 29)

In [37]:
cleaned_data = data.to_csv("food_delivery_clean_colab_data.csv", index=False)